// Import necessary fonts from Google using Next.js Font optimization
import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css";  // Import custom global styles

// Configure the Geist font (sans-serif style)
const geistSans = Geist({
  variable: "--font-geist-sans",  // Create a custom CSS variable for the font
  subsets: ["latin"],  // Specify that the Latin subset should be loaded
});

// Configure the Geist_Mono font (monospace style)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // Create a custom CSS variable for the font
  subsets: ["latin"],  // Specify that the Latin subset should be loaded
});

// Metadata for the app (this can be used for SEO purposes)
export const metadata = {
  title: "Create Next App",  // Title of the web app
  description: "Generated by create next app",  // Description for SEO
};

// Main root layout component
export default function RootLayout({ children }) {
  return (
    <html lang={"en"}>{/* Set language of the document to English */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}  // Apply the fonts and add anti-aliasing for smooth text rendering
      >
        {children}  {/*Render child components here */}
      </body>
    </html>
  );
}
