version: '3.8'
services:
  backend:
    build: ./backend
    container_name: online-exam-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo-db
    networks:
      - exam-network

  frontend:
    build: ./online-exam-frontend
    container_name: online-exam-frontend
    ports:
      - "3000:3000"
    networks:
      - exam-network

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - exam-network

volumes:
  mongo-data:

networks:
  exam-network:
    driver: bridge

